samples: "samples.tsv"

reference:
  fasta: ""

cnvkit:
  pon: ""

cnvnator:
  pon: ""

manta:
  pon: ""

smoove:
  exclude: ""

tiddit:
  pon: ""

tools:
  cnvkit: "docker://marrip/cnvkit:0.9.7"
  cnvnator: "docker://marrip/cnvnator:0.4.1"
  common: "docker://marrip/common:1.1.0"
  manta: "docker://marrip/manta:v1.6.0"
  tiddit: "docker://marrip/tiddit:2.12.1"
