samples: "samples.tsv"

reference:
  fasta: "reference/WASH7P.fna"

smoove:
  exclude: "reference/exclude.bed"

tools:
  cnvnator: "docker://marrip/cnvnator:0.4.1"
  common: "docker://marrip/common:1.1.0" 
  manta: "docker://marrip/manta:v1.6.0"
  tiddit: "docker://marrip/tiddit:2.12.1"
