samples: "samples.tsv"

reference:
  fasta: "reference/WASH7P.fna"

cnvkit:
  pon: "reference/cnvkit_somatic_pon.cnn"

cnvnator:
  pon: "reference/cnvnator.bed"

manta:
  pon: "reference/manta.bed"

smoove:
  exclude: "reference/exclude.bed"

tiddit:
  pon: "reference/tiddit.bed"

tools:
  cnvkit: "docker://marrip/cnvkit:0.9.9"
  cnvnator: "docker://marrip/cnvnator:0.4.1"
  common: "docker://marrip/common:1.1.0" 
  manta: "docker://marrip/manta:v1.6.0"
  tiddit: "docker://marrip/tiddit:2.12.1"
